apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-simple-build-owhs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-simple-build-owhs
    app.kubernetes.io/part-of: build-suite-test-application-uebr
  name: test-simple-build-owhs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-simple-build-owhs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-simple-build-owhs
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-rnzs-tenant/build-suite-test-application-uebr/test-simple-build-owhs@sha256:c3057235e47861641eaea1d80153db73cbb8200d16f22f25b7bc07acaf4502f6
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
